In [3]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a.itemsize)

2
4


In [7]:
import numpy as np
a = np.array([[1,2,3]])
print(a.itemsize)
print(a.dtype)

4
int32


In [9]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7]])
print(a.shape)
print(a.size)

(1, 7)
7


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print("Before reshaping")
print(a)
a=a.reshape(3,2)
print("After reshape")
print(a)

Before reshaping
[[1 2 3]
 [4 5 6]]
After reshape
[[1 2]
 [3 4]
 [5 6]]


In [12]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a[0,2])
print(a[1,1])

3
5


In [13]:
import numpy as np
a = np.linspace(5,15,10)
print(a)

[ 5.          6.11111111  7.22222222  8.33333333  9.44444444 10.55555556
 11.66666667 12.77777778 13.88888889 15.        ]


In [16]:
import numpy as np
a = np.array([2,3,7,11,45,21])
print("Array :",a)
print("Maximum :",a.max())
print("Minimum :",a.min())
print("Sum :",a.sum())

Array : [ 2  3  7 11 45 21]
Maximum : 45
Minimum : 2
Sum : 89


In [17]:
import numpy as np
a = np.array([[2,3,4],[43,23,13]])
print(a)
print(a.max(axis=0))
print(a.min(axis=1))
print(a.sum(axis=1))

[[ 2  3  4]
 [43 23 13]]
[43 23 13]
[ 2 13]
[ 9 79]


In [18]:
import numpy as np
a = np.array([[2,3,4],[43,23,13]])
b = np.array([[1,2,3],[4,5,6]])
print("Sum of two arrays :",a+b)
print("Product of two arrays :",a*b)
print("Division of two arrays :",a/b)

Sum of two arrays : [[ 3  5  7]
 [47 28 19]]
Product of two arrays : [[  2   6  12]
 [172 115  78]]
Division of two arrays : [[ 2.          1.5         1.33333333]
 [10.75        4.6         2.16666667]]


In [22]:
import numpy as np
a = np.array([[2,3,4],[43,23,13]])
b = np.array([[1,2,3],[4,5,6]])
print("Vertically stacked",np.vstack((a,b)))
print(np.hstack((a,b)))

Vertically stacked [[ 2  3  4]
 [43 23 13]
 [ 1  2  3]
 [ 4  5  6]]
[[ 2  3  4  1  2  3]
 [43 23 13  4  5  6]]


In [24]:
import numpy as np
arr = np.empty((3,2),dtype=int)
print(arr)

[[-42418480       522]
 [        0         0]
 [        1   6488147]]


In [26]:
import numpy as np
arr = np.zeros((3,2),dtype=int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [27]:
import numpy as np
arr = np.ones((3,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [29]:
import numpy as np
l = [1,2,3,4,5,6]
a = np.asarray(l)
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [30]:
import numpy as np
t = (1,2,3,4,5,6)
a = np.asarray(t)
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [31]:
import numpy as np
l = [[1,2,3,4,5,6],[7,8]]
a = np.asarray(l)
print(a)
print(type(a))

[list([1, 2, 3, 4, 5, 6]) list([7, 8])]
<class 'numpy.ndarray'>


C:\Users\Bhavya Kansara\anaconda3\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [33]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
import numpy as np
a = np.random.rand(5,2)
print(a)

[[0.43080806 0.91432002]
 [0.58291896 0.90690118]
 [0.64581723 0.94583444]
 [0.98255398 0.63695623]
 [0.6463951  0.09429699]]


In [38]:
import numpy as np
a = np.random.randn(5,2)
print(a)

[[-0.16944522 -0.19618452]
 [-0.38574569  1.26286955]
 [-0.06578507  0.42223246]
 [ 0.75519932 -1.28724677]
 [ 0.37326426  0.06025885]]


In [41]:
import numpy as np
a = np.random.randint(3,size=5)
print(a)

[2 0 1 0 1]


In [42]:
import numpy as np
a = np.random.random_integers(3)
b = np.random.random_integers(5,size=(3,2))
print(a)
print(b)

3
[[3 2]
 [5 5]
 [4 5]]


<ipython-input-42-043000484baf>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  a = np.random.random_integers(3)
<ipython-input-42-043000484baf>:3: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  b = np.random.random_integers(5,size=(3,2))


In [43]:
import numpy as np
a = np.random.choice(4,3)
a

array([2, 0, 1])

In [45]:
import numpy as np
a = np.random.bytes(7)
a

b'\xdd\xd9x\x07\xe3\xeax'

In [47]:
import numpy as np
a = np.arange(12)
print(a)
np.random.shuffle(a)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 1,  0,  5,  4,  2,  7,  8,  6, 10,  9, 11,  3])

In [48]:
import numpy as np
a = np.array([2,4,6,3**8])
print(a)
b = np.log(a)
print(b)
c = np.log2(a)
print(c)
d = np.log10(a)
print(d)

[   2    4    6 6561]
[0.69314718 1.38629436 1.79175947 8.78889831]
[ 1.          2.          2.5849625  12.67970001]
[0.30103    0.60205999 0.77815125 3.81697004]


In [49]:
import numpy as np
a = np.arange(12)
print(a)
b = np.where(a<6,a,5*a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5 30 35 40 45 50 55]
